// Game Unfolding Machine v2.2 — every table, grouped by the book's own sections.
// GUM is prep-time: it fills the blanks PUM's plot sheets and SUM's scenes expect
// you to have already written. It is a supplement, not a system.
//
// Rows are plain lists indexed 1..N; the die size is the row count (d20 or d100).
// Extracted by the bbox reconstruction in tests/tools/, row counts and numbering
// verified contiguous before transcription.

export const GUM_SECTIONS = [
  { id: "seeding",   name: "Game seeding",     pages: "4-7",   blurb: "Where a game comes from: the world's truths, and the seed of a plot." },
  { id: "world",     name: "World generator",  pages: "8-13",  blurb: "Factions, locations, objects, a nemesis, and the creatures in between." },
  { id: "character", name: "Character builder",pages: "14-21", blurb: "People — what marks them, what undoes them, and what they are for." },
  { id: "grand",     name: "Grand oracle",     pages: "22-24", blurb: "Action, adjective, subject. Three words for when nothing else fits." },
];

export const GUM_TABLES = [
  {
    id: "location-archetype", section: "seeding", group: "World truths", page: 4, die: 20,
    name: "Location archetype",
    blurb: "The setting of your game and the environment it takes place in. Roll several times to mix and match features.",
    rows: [
      "Humid: Wilderness, jungle, raining, rivers, marshes, falls", "Forgotten: Ruins, outpost, camp, fortress, military base, castle",
      "Urban: Metropolis, city, lively place, traffic jams, sprawl, business", "Hidden: Cave, underground, underworld, tunnels, darkness, deep",
      "Strange: Alien, new lands, unfamiliar, colony, discovery, exploration", "Specialized: Research facility, school, laboratory, magic academy",
      "Wilderness: Dry steppes, forest, deep woods, rivers, plains, mud", "Heat: Hot region, desert, oasis, tundra, arid plains, sands, dust",
      "Rough: Mountains, hills, snowy peaks, strong winds, rocks, cliffs", "Busy: Trade routes, roads, in a journey, traveling, moving",
      "Water: Ocean, islands, sea, underwater, port, sea world, coast", "Outskirts: Remote town, village, ghost town, old farms, wasteland",
      "Indoors: Manor, a mansion, hotel, residence, tavern, large building", "Cold: Snow, tundra, very cold, freezing conditions, blizzard",
      "Social: Neighbor, ghetto, red alert zone, low suburbs, packed", "Secret: Guild or faction headquarters, facility, station, hideout",
      "Beyond: Elevated, tower, flying, aircraft, spaceship, space station", "Army: Military, barracks, fortress, carrier, submarine, warship",
      "Captive: Prison, captive, police station, dungeon, courts, locked", "Dangerous: Rough, volcanic, hazardous, earthquake, rocky, burning",
    ],
  },
  {
    id: "background-problem", section: "seeding", group: "World truths", page: 5, die: 20,
    name: "Background problem",
    blurb: "The world's current state — the background that shapes atmosphere, global challenges and power dynamics.",
    rows: [
      "Government: Oppression, tyranny, there’s a problematic leader, the situation is dire", "Safety: High crime, violence, murders, gangs, mobs, anarchy, there is no law",
      "Special: Something extremely important, or valuable, is lost, or has been stolen", "Together: Common enemy, global threat building up, and is going to affect us all",
      "Struggle: There is a confrontation of two local factions for power, enemies within", "Unavoidable: Natural disaster, catastrophe, terrible weather, doom, damage control",
      "Punishment: Plague, curse, damnation, sickness, disease, we are helpless, we are dying", "Secrecy: Secret organizations, rumors, intelligence, espionage, we’re being watched",
      "Confusion: What used to work isn’t working anymore, failure, ignorance, powerless", "Blame: Since an object was discovered or brought here, everything is wrong",
      "Strength: Large scale conflict, war, lack of supplies, hardship, need to work together", "Innocence: Endangered tribe, species, creature, animals, or a similar vulnerable group",
      "Victims: Kidnapping, disappearances, it matters; these are valuable people to us", "Hypocrisy: Corruption everywhere, tax pressure, hunger, injustice, oppression",
      "Sabotage: Trade routes troubled, lack of supplies, a siege, raiders, pirates, monsters", "Cosmic: Weird event happened, phenomenon, feels very strange, something not right",
      "Injustice: Lack of good morals, segregation, hunger, poverty, the rich and the poor", "Voice: Uprising, rebellion, revolution, riots, the people, bring the powerful down",
      "Panic: Chaos, despair, pandemonium, outsiders, aliens, survival, the apocalypse", "Belief: Religious oppression, holy war, inquisition, extremists, prophecies, divine",
    ],
  },
  {
    id: "plot-hook", section: "seeding", group: "Plot seed", page: 6, die: 20,
    name: "Plot hook",
    blurb: "What pulls the protagonists in.",
    rows: [
      "Someone made a big sacrifice today", "Someone well connected makes an offer",
      "Conflict reached a peak tension state", "Someone in power gives you an order",
      "It’s a life-or-death matter, you in danger", "Formal request, a petition, royal mandate",
      "Invited to a private meeting, it’s important", "You are being watched, or followed",
      "What happened became now personal", "Terrible event related to the world truths",
      "A finding that could change everything", "A desperate or urgent request for help",
      "Condition to join a faction, or faction ask", "Found a map or anonymous instructions",
      "You were in the wrong place and time", "A paid job, there’s a big reward involved",
      "Family petition, yours, or someone else’s", "You are attacked, or directly endangered",
      "Found a corpse, crime scene, or witness", "There is a conflict, you have to pick sides",
    ],
  },
  {
    id: "motivation", section: "seeding", group: "Plot seed", page: 6, die: 20,
    name: "Motivation",
    blurb: "Why they take it on.",
    rows: [
      "A matter of money, debt, wrong people", "A matter of promises, vows, duty, loyalty",
      "You have no choice, it has to be you", "You are forced to do it, mandate",
      "Helps a world truth background problem", "Prevents a world truth issue to get worse",
      "You get paid, a very tempting reward", "Keep whatever you find along the way",
      "Avoid someone getting really angry", "A relationship matter, someone you care",
      "A personal matter, backstory related", "Reveal a world’s secret or valuable lore",
      "Trigger a drastic world changing element", "Become powerful, gain status, or position",
      "A unique artifact or object to be found", "Prevent great harm from being done",
      "Be able to come back home or to family", "Unlock business or trade opportunity",
      "Achieve happiness, alleviate pain, find hope", "Don’t know why, just do it, understand later",
    ],
  },
  {
    id: "mission", section: "seeding", group: "Plot seed", page: 6, die: 20,
    name: "The mission",
    blurb: "What they are actually being asked to do.",
    rows: [
      "Capture an enemy, dead or alive", "Defeat a faction, bandits, or outlaws",
      "Discover who is behind a problem", "Sabotage or infiltrate enemy operation",
      "Retrieve an important or unique artifact", "Stop someone from doing wrong",
      "Look for proof or evidence in a location", "Rescue someone from trouble",
      "Destroy an objective, object, or location", "Spy on someone to confirm suspicion",
      "Find a tool or weapon to make use of it", "Transport someone to safety",
      "Protect a group in disadvantage", "Prevent an imminent planned attack",
      "Secure or defend a strategic location", "Assault a moving convoy or target",
      "Scout a location to help a faction attack", "Reveal or divulge a truth or propaganda",
      "Convince them to change their mind", "Fulfill a prophecy, or a backstory goal",
    ],
  },
  {
    id: "initial-lead", section: "seeding", group: "Plot seed", page: 7, die: 20,
    name: "Initial lead",
    blurb: "The first thread to pull — this can shape your opening scene.",
    rows: [
      "Someone died recently, a crime scene", "Coordinates of a strategic location given",
      "Someone in danger to help and talk to", "There is a source of information nearby",
      "Relevant people about to meet secretly", "A location about to be targeted by enemy",
      "An unhelpful witness who won’t talk", "Official evidence is handed over to you",
      "Investigate location of a recent event", "Enemy abandoned or changed location",
      "Enemy next move has been revealed", "Something out of control to be stopped",
      "We have a prisoner who won’t talk", "An announcement seems contradictory",
      "Someone disappeared, or went missing", "Track an agent, thief, escaping prisoner",
      "We received a letter, but it is incomplete", "Confirmed the location of a key object",
      "Someone is willing to betray our enemy", "An enemy weakness has been revealed",
    ],
  },
  {
    id: "caveat", section: "seeding", group: "Plot seed", page: 7, die: 20,
    name: "Caveat",
    blurb: "A complication known from the start.",
    rows: [
      "We don’t know where the target is", "Target is always moving, unpredictable",
      "Sensitive third party getting involved", "Divided opinions. Enemy needed/justified",
      "Got competition, be careful, stop them", "Background problem actively in your way",
      "Lack of loyalty, trust, or confidence in you", "Rough beginning, start at a disadvantage",
      "Family member involved (is it your own?)", "We are still missing some names",
      "Too many uncertainties, stay low profile", "No killings (at least no innocent’s lives)",
      "We know where, but hard to get there", "Transport or travel routes compromised",
      "Someone powerful is behind everything", "Legendary enemy allied to their cause",
      "Hazardous location conditions or traps", "Unknown vulnerabilities, needs intel",
      "We aren’t ready yet. Needs preparation", "We are under time pressure or limit",
    ],
  },
  {
    id: "opposition", section: "seeding", group: "Plot seed", page: 7, die: 20,
    name: "The opposition",
    blurb: "Who stands against the characters, and what makes them hard.",
    rows: [
      "They have plenty of minions to stop you", "They have the police/guards on their side",
      "They have government/official support", "They made arrangements with hirelings",
      "They have agents in disguise on your hunt", "They have eyes and ears everywhere",
      "They are rich, and very resourceful", "They are politically very powerful",
      "They have powerful agents with abilities", "They are aware of you, or expecting you",
      "You are very outnumbered by them", "You have a relationship with one of them",
      "You have something that bothers them", "Your backstory is causing them trouble",
      "Your backstory is causing you trouble", "You aren’t sure how or where they operate",
      "You have a friend, or family, on their side", "You could use a specific faction’s help",
      "You need a special object to defeat them", "You’ll need a good network to find them",
    ],
  },
  {
    id: "faction-focus", section: "world", group: "Faction", page: 8, die: 20,
    name: "Current driving focus",
    blurb: "What this faction wants above all.",
    rows: [
      "Revenge: Has been recently or historically offended", "Survival: Struggles to survive and is ready to do anything",
      "Liberation: Desire to free themselves or another group from tyranny", "Exploration: Seeks new lands, adventure, geographic knowledge",
      "Discovery: Search of lost artifacts, hidden knowledge, and secrets", "Innovation: Invested in development and research of technology or magic",
      "Preservation: Protect or restore endangered, ancient, or sacred value", "Transformation: Seeks deeply to transform the world in their ways",
      "Ascension: Aims to achieve a higher state of being, power, or enlightenment", "Redemption: Lives for the forgiveness of their soul and others",
      "Domination: Conquer or control other factions, territories, resources", "Expansion: Expand borders, influence, or population by diplomacy or colonization",
      "Revolution: Rebels who want to break an established order, system, or authority", "Restoration: Come back to their former glory, order, and restore the balance",
      "Creation: Focus on the creation or design of life, architecture, art, or culture", "Destruction: Considers everything as old, ugly and harmful, as threatening to them",
      "Unification: Seeks the reconciliation of different factions and stop conflicts", "Separation: Seeks to become independent and isolated from other groups",
      "Harmony: Search for spiritual, mental, or inner peace, within themselves or others", "Chaos: Sows discord, conflict, and disorder among themselves and others",
    ],
  },
  {
    id: "faction-resource", section: "world", group: "Faction", page: 8, die: 20,
    name: "Surpluses or needs",
    blurb: "A resource they have in abundance — or badly lack. You decide which.",
    rows: [
      "Wealth: Money, gold, reserves, or other assets that they can use to trade and control others", "Military: Well-trained, or well-equipped forces to fight, defend, or intimidate their enemies",
      "Magic: Powerful, rare, or forbidden magic to cast spells, enchant objects, or manipulate reality", "Intelligence: Knowledge, or wisdom to solve problems, devise plans, or outsmart rivals",
      "Culture: Rich, diverse, or influential culture to inspire, attract, or assimilate others", "Religion: Strong, devout, or charismatic faith to motivate, heal, or convert others",
      "Diplomacy: Good reputation, network, or alliances to negotiate, cooperate, or trade with others", "Technology: Advanced, innovative technology to invent, build, or improve things",
      "Nature: Affinity with nature to communicate, control, or transform animals or plants", "Art: Talent, skill, or passion for art that they can use to create, express, or impress others",
      "Education: High level of literacy, learning, or teaching to read, write, or educate others", "Medicine: Knowledge of anatomy and resources to heal, cure, or prevent diseases or injuries",
      "Energy: Large amount of power resources to generate electricity, build, or run machines", "Trade: Stability, goods, services, or markets that they can use to sell and buy things",
      "Law: Fair and effective system of rules and regulations to maintain order and justice", "History: Long and glorious past to remember and honor their ancestors and traditions",
      "Prophecy: Prediction of the future they use to guide and prepare themselves and others", "Secret: A hidden or unknown advantage to surprise and confuse their enemies",
      "Loyalty: Strong bond of trust and respect among its members to support each other", "Diversity: Variety of races, genders, classes, or abilities to complement and enrich each other",
    ],
  },
  {
    id: "faction-society", section: "world", group: "Faction", page: 9, die: 20,
    name: "by society",
    blurb: "How their society is shaped.",
    rows: [
      "Small, independent groups with diverse ways", "Strict social classes, rigid roles, and moral code",
      "Emphasis on community and shared goals", "Culture is defined by creativity and performance",
      "A dominant faith shapes all aspects of life", "Obsession with science, innovation and progress",
      "History and knowledge passed down in stories", "Emphasis on combat and physical prowess",
      "Technologically integrated and progress-centric", "Diverse cultures interacting through trade",
      "Secret organizations with their own agendas", "No innovation or change, stuck in the old ways",
      "Blend of multiple cultures into a unique identity", "Marginalized groups living on the fringes",
      "Constant movement, change, and adaptation", "Reverence for the mystical or ancient spirits",
      "Culture is focused on amusement and spectacle", "Deep connection to animals or the natural world",
      "Built on a unique social or political philosophy", "Falling apart and in decay, to dissolve in chaos",
    ],
  },
  {
    id: "faction-beliefs", section: "world", group: "Faction", page: 9, die: 20,
    name: "by beliefs",
    blurb: "What they hold sacred or true.",
    rows: [
      "Reverence for the spirits of the dead and afterlife", "Belief that all things possess a spirit or soul",
      "The balance of opposing forces, good and evil", "Multiple deities with distinct domains and figures",
      "Belief in a single, all-powerful monotheistic deity", "Deification of natural forces and elements",
      "Maintaining harmony within the universe", "Predetermined events and divine guidance",
      "The cyclical rebirth of souls and reincarnation", "Emphasis on reason, logic, and ethical principles",
      "Worship of a charismatic leader or figure", "Esoteric beliefs, rituals, and exotic practices",
      "Atheistic, belief in mindfulness and individuality", "Life is a series of trials to prove worthiness",
      "Influence of celestial bodies and the universe", "The search of power, spells and incantations",
      "Everyone possesses a spark of the divine", "Belief in an impending end of the world",
      "The power of technology as a divine force", "Blending of multiple religious traditions",
    ],
  },
  {
    id: "faction-politics", section: "world", group: "Faction", page: 9, die: 20,
    name: "by politics",
    blurb: "How power and economy actually work there.",
    rows: [
      "No single ruling authority, fairly democratic", "A powerful single ruler or figure of reference",
      "Economy relies heavily on exterior commerce", "Struggle for the limited resources and survival",
      "Wealth generated from natural resources", "Frequent political struggles and conflicts",
      "Inefficient and heavily corrupt government", "Rule through force and military troops",
      "Religious leaders hold the political power", "Rule by a small, elite group, aristocrats",
      "Exchange based trading, weak economy", "Strong currency that facilitates trade",
      "Central controlled production and distribution", "Minimal intervention in economy and society",
      "Trade and crafts are controlled by guilds", "Region controlled by an outside power",
      "Complex network of treaties, bureaucratic", "Powerful criminal organizations region control",
      "Scientists or engineers hold political power", "Widespread poverty and ruin, weak politics",
    ],
  },
  {
    id: "location-feature", section: "world", group: "Location", page: 10, die: 20,
    name: "by feature",
    blurb: "What marks this place out.",
    rows: [
      "Belongs to a faction, headquarters, base", "Legends, history, mythological, hidden",
      "Inhospitable, hazardous, unholy, forbidden", "Dangerous, full of traps, enemies, leaders",
      "Secured, defended, watched, monitored", "Secretive, hidden, camouflage, unreachable",
      "Unstable, crumbling, damaged, falling", "Magical, supernatural, esoteric, evil",
      "Sabotaged, sacked, raided, destroyed", "Disputed, in conflict, under battle",
      "Destroyed, ruined, difficult to traverse", "Hazardous, bad weather, or atmosphere",
      "Horrid, bloody, fearful, scary, terror", "Technological, special, advanced, technical",
      "Abandoned, left behind, worthless", "Forbidden, sacred, holy, divine, special",
      "Normal, regular, simple, common, clean", "Isolated, aside, lonely, empty, distant",
      "Different, new, unique, mysterious, elegant", "Bad reputation, bad people, illegal",
    ],
  },
  {
    id: "location-purpose", section: "world", group: "Location", page: 10, die: 20,
    name: "by purpose",
    blurb: "What it exists to do.",
    rows: [
      "Communication, intel, radio, coordination", "Security, overwatch, visibility, vigilance",
      "Defense, military, weapons, protection", "Transport, vehicles, aircraft, garage, launch",
      "Experiments, laboratory, research, study", "Storage, warehouse, supplies, resources",
      "Medicine, healing, recovery, treatment", "Power supply, energy source, power plant",
      "Repairing, workshop, construction, facility", "Hospitality, food, sleep, drinks, socializing",
      "Educate, training, qualification, practice", "Primary goods, farming, animals, mining",
      "Popular, festivities, rituals, praying, sacrifice", "Events, meeting, planning, decision making",
      "Production, manufacturing, assembly, build", "Imprisonment, dungeon, torture, guarding",
      "Trading, business, exchange, banking", "Sports, entertainment, amusement, sexual",
      "Safety, security, secrecy, protection, hiding", "Home, residence, privacy, property, owner",
    ],
  },
  {
    id: "location-worth", section: "world", group: "Location", page: 10, die: 20,
    name: "by worth",
    blurb: "Why anyone would want it.",
    rows: [
      "Geopolitical value, diplomacy, embassy", "Sacred, divine, holy, relics, artifacts",
      "Unique, artistic, architecture, design", "Storage of wealth, money, treasure",
      "Minerals, resources, materials, crafting", "Technology, research, machinery, robotics",
      "Important people, elitist, unique, fancy", "Strategic place for business or tourism",
      "Military strategic, bottleneck, position", "Trade routes, commerce, international",
      "Strategic nature, water, food, life, supplies", "Intrinsic value, highly demanded, desired",
      "Industrial power, production, supply chain", "Magical, special, esoteric, source, secret",
      "Historical purpose, culturally valuable", "Well-connected, routes, trades, logistics",
      "Knowledge source, records, documents", "Nature, paradise like, unique geography",
      "Elevated position, or flying, visibility", "Fertile, land, food, production, resources",
    ],
  },
  {
    id: "location-content", section: "world", group: "Location", page: 10, die: 20,
    name: "by content",
    blurb: "What is actually in there.",
    rows: [
      "Enemies, beasts, sentient beings, fauna", "Organic forms, fungus, plants, flora",
      "Supplies, resources, food, water, energy", "Traps, dangers, hazards, harmful things",
      "Knowledge, literature, intel, data, information", "Weapons, defense, armory, ammunition",
      "Wealth, valuables, treasure, riches, possession", "Clues, leads, a map, coordinates, puzzle, riddle",
      "Tools, crafting, batteries, material, ingredients", "Healing, potions, herbs, medicine, pharmacy",
      "Magic, wonder, weird, unexpected, esoteric", "Technology, plans, design, robotics, implants",
      "Research material, experiments, interrogation", "Corpses, dead bodies, leftovers, remnants",
      "Art, music, smells, tastes, sound, noise, paint", "Religious artifacts, symbols, offerings, rituals",
      "Darkness, invisible, hard to see, fuzzy, nothing", "People, refugees, social, networking, comms",
      "Machinery, equipment, construction, buildings", "Nature, rocks, dust, flood, wind, fog, dirt",
    ],
  },
  {
    id: "object-function", section: "world", group: "Object", page: 11, die: 20,
    name: "by function",
    blurb: "What the object does.",
    rows: [
      "Defend, protect, alert, detect, cover", "Attack, hurt, damage, pierce, kill",
      "Emit sound, music, alarm, resonance", "Emit signal, waves, radar, invisible forces",
      "Transmit, collect, or record information", "Store, save, accumulate, collect",
      "Clean, remove, reset, maintain, restore", "Emit heat, warmth, energy, electricity, charge",
      "Transport, move, load, teleport, send", "Channel electricity, magic, or faith",
      "Craft, build, construct, repair, replace", "Communicate, connect, reach, link, bridge",
      "View, scan, explore, scout, view, zoom", "Hear, listen, record, audio related",
      "Cool, freeze, chill, fortify, strengthen", "Explode, destroy, shatter, break",
      "Produce radiation, sicken, corrode", "Poison, immobilize, trap, hinder",
      "Support, help, enhance, improve, reinforce", "Give faith, hope, heal, restore",
    ],
  },
  {
    id: "object-state", section: "world", group: "Object", page: 11, die: 20,
    name: "by state",
    blurb: "The condition it is in.",
    rows: [
      "Broken, damaged, impaired, incomplete", "Locked, protected, secured, blocked",
      "Being used, active, mounted, equipped", "Scanning, detecting, watching, recording",
      "New, released, promoted, opened, launched", "Used, discharged, wasted, emptied, depleted",
      "Stolen, taken away, sent, sold, moved", "Bought, acquired, found, recently discovered",
      "Analyzed, researched, studied, cracked open", "Connected, plugged, attached, linked",
      "Sending signal, emitting, transferring", "Protecting, defending, saving, storing",
      "Helping, healing, reinforcing, restoring", "Channeling, processing, empowering",
      "Disabled, passive, turned off, shut down", "Holding, sustaining, supporting, standing",
      "Private property, claimed, unique, valuable", "Public property, shared, common, regular",
      "Disputed, conflicted, divided, claimed", "Weakened, low-charge, last minutes",
    ],
  },
  {
    id: "object-form", section: "world", group: "Object", page: 11, die: 20,
    name: "by form",
    blurb: "What it looks and feels like.",
    rows: [
      "Shiny, light-emitting, bright, white", "Colorful, eye-catching, vibrant",
      "Hi-tech, digital, sensor, wave", "Geometric, symmetric, artistic",
      "Vibrating, moving, shaking, unstable", "Rusty, rotten, decomposing, smelly",
      "Furry, hairy, warm, fluffy", "Metallic, hard, heavy, solid",
      "Liquid, wet, humid, adaptable", "Spiky, pointy, sharp, edgy",
      "Sticky, glue, gruesome, gross", "Magnetic, pull, push, repel, attract",
      "Electric, charged, loaded, exploding", "Organic, living, alive, breathing",
      "Reacting, shaking, sensitive", "Moving, floating, flying, hovering",
      "Noisy, loud, flashy", "Soft, bland, fragile, glass",
      "Gaseous, ethereal, transparent", "Magical, divine, prophetic, esoteric",
    ],
  },
  {
    id: "nemesis-deeds", section: "world", group: "Nemesis", page: 12, die: 20,
    name: "by past deeds",
    blurb: "What they have already done.",
    rows: [
      "Found, or stole something of importance", "Made the wrong choice, or a bad deed",
      "Learned a new skill, power, ability, mutation", "Trapped, captured, or kidnapped someone",
      "Blocked, sabotaged, or intercepted a route", "Unleashed havoc, disaster, chaos, destruction",
      "Disobeyed, broke a promise or pact, betrayed", "Spread a curse, madness, poison, their word",
      "Denied a truth, was found innocent, told lies", "Leaked or sold out important information",
      "Committed a murder, or sent an order to", "Destroyed or damaged something of value",
      "Injured or caused harm to someone", "Destroyed information, data, or evidence",
      "Damaged a location, area, or building", "Claimed, captured, or sieged a location",
      "Sabotaged or interrupted your next move", "Converted someone to their cause",
      "Equipped themselves with a new weapon", "Openly declared war, or attacked a faction",
    ],
  },
  {
    id: "nemesis-impression", section: "world", group: "Nemesis", page: 12, die: 20,
    name: "by impression",
    blurb: "The feeling their presence transmits.",
    rows: [
      "Feelings of fear, worry, alert, concern", "Excitement, anxiety, nerves, impatience",
      "Acts to cause sadness, disgust or shame", "Feelings of disbelief, or disappointment",
      "Achievements produce awe and wonder", "A presence that causes lose of hope",
      "Envy, jealousy, resentment to be felt", "Outer or inner warmth, heat, fire, resent",
      "Rumble of weather, divine forces, doom", "Sudden, hushing silence embraces you",
      "Smells and ingredients in preparation", "Atmosphere of groom, grief, or regret",
      "Murmur, whispering, strange voices", "Melody, a song, bells, rhythm, music",
      "Cold, freezing and shivering sensations", "Inner voices, static, psychic, autism",
      "Feel hate, anger, fury, rage, vengeance", "A strange, eccentric look, observed",
      "Mechanical, magical, or buzzing sounds", "Hateful admiration for their powers",
    ],
  },
  {
    id: "nemesis-intentions", section: "world", group: "Nemesis", page: 12, die: 20,
    name: "by their intentions",
    blurb: "What they mean to do to you next.",
    rows: [
      "Get you stuck, capture, or trap you", "Hurt innocents, or put them in danger",
      "Make an ambush, or sneak attack", "Attack you directly anytime soon",
      "Discover or exploit your weakness", "Give you a last warning or threat",
      "Escape, escape, become harder to find", "Harm your relations, or diplomacy",
      "Endanger or damage an object of value", "Call for help, reinforcements, alarm",
      "Take, damage, sabotage a key location", "Capture or imprison someone relevant",
      "Kill, execute, order an assassination", "Put a trade route or business at risk",
      "Publicly reveal or expose your plans", "Buy time, wait for you to make a mistake",
      "Cause your equipment, or vehicle to fail", "Gather, find, or summon new allies",
      "Trigger hazards, set a trap, set on fire", "Lead to a bloody battle or attack",
    ],
  },
  {
    id: "creature-type", section: "world", group: "Creature", page: 13, die: 20,
    name: "by type",
    blurb: "Its bodily nature.",
    rows: [
      "Reptilian, dragon like, scales, hard skin, ugly", "Abnormally large insect, horrid, many eyes",
      "Winged, hairy, with a tail, thick, large, beast", "Flesh, putrid, undead, scary, zombie, life-mimic",
      "Tentacles, weird extensions, many extremities", "Skeleton, bone-based, hard, breakable",
      "Plant-like, fungus, flora, grows, nature-based", "Robotic, armored, golem, strong, controlled",
      "Shapeshifter, multiple forms, adaptable, regen", "Worm-like, squeezy, bland, disgusting, smelly",
      "Ghostly, transparent, ethereal, invisible, spirit", "Mutated, transformed, deformed, improved",
      "Vampiric, bloody, biting, eating, fangs", "Werewolf, monstruous, humanoid, beast",
      "Mermaid, charming, mind-control, seducing", "Gargoyle, stone-form, thick, shell, armor",
      "Flying, agile, fast, nimble, jumping, displace", "Beast, large, monstrous, animalistic, barbaric",
      "Swarm, insect-like, very small, bacteria, virus", "Amorphic, liquid, ooze, wind-based, thoughts",
    ],
  },
  {
    id: "creature-behavior", section: "world", group: "Creature", page: 13, die: 20,
    name: "by behavior",
    blurb: "How it acts and thinks.",
    rows: [
      "Sentient being, language-capable, developed", "Instinct-based, animalistic, emotional, noisy, loud",
      "Intelligent animal, survival focused, eats a lot", "Primitive, ritualistic, artistic, prophetic, holy",
      "Above human intelligence, computer based?", "Hive-mand, pack based, moves in groups",
      "Industrious, builder, coordinated, worker, slave", "Aggressive, attacker, predator, hunger, anger",
      "Defensive, protecting, territorial, and tough", "Avoids aggression at all costs, yet very capable",
      "Coward, squishy, runs away, avoids contact", "Family-centric, protector, leader, social, helpful",
      "Symbiote, attaches itself to things or others", "Intimidating, scary, loud, alpha-like, arrogant",
      "Lonely, lone-wolf, avoids social interactions", "Unstable, chaotic, unpredictable, roaming",
      "Explorer, curious, stalker, moving, migrating", "Passive, peaceful, ignoring, oblivious",
      "Nature-oriented, biome-specific, grounded", "Dependent, needs others, or mineral to survive",
    ],
  },
  {
    id: "creature-ability", section: "world", group: "Creature", page: 13, die: 20,
    name: "by ability",
    blurb: "What makes it dangerous.",
    rows: [
      "Physical, strong, tough, heavy, charge", "Psychological attack, intimidation, gaze",
      "Specially resistant to physical damage", "Resistant to specific elements",
      "Flying, fast moving, teleportation, nimble", "Moves in non-air space, water, space",
      "Enhanced senses, smell, hearing, feel", "Invisible, concealment, camouflage",
      "Poison or disease based attacks", "Makes uses of crafty tools and gear",
      "Tactical, strategic, ambushing, distracts", "Paralyzing, crippling, or entangling attacks",
      "Biologically enhanced, mutation, on drugs", "Defensive, dodging, very agile, fast",
      "Summons, invoke others, calls for help", "Ranged attacks, distant, long-sight",
      "Frightening, scary, shocking, taunting", "Climber, tunneling, uses the terrain",
      "Overpowered weapon or piece of gear", "Triggers a special mode or transformation",
    ],
  },
  {
    id: "character-edge", section: "character", group: "Character", page: 14, die: 20,
    name: "by their edge",
    blurb: "What distinguishes them.",
    rows: [
      "Naturally draws others in, persuasive and likable", "Quick-thinking and skilled at finding solutions",
      "Endures mental or physical hardships", "Faces danger head-on without hesitation",
      "Notices small details others often overlook", "Talks through difficult situations with ease",
      "Always one step ahead, strategic and calculating", "Fiercely devoted, unwilling to betray trust",
      "Willing to wait for the right opportunity, patient", "Self-sufficient, rarely relying on others",
      "Very resolute, makes the most of any situation", "Stays calm and collected under pressure",
      "Reads people well, understands emotions", "Strives for greatness, never satisfied",
      "Always ready with a sharp response or remark", "Adjusts quickly to changing circumstances",
      "Holds firm to beliefs, values, and promises", "Hard to read, intriguing and unpredictable",
      "Lightens tense situations with humor or mischief", "Takes risks without hesitation, dares to stand up",
    ],
  },
  {
    id: "character-flaw", section: "character", group: "Character", page: 14, die: 20,
    name: "by their flaw",
    blurb: "What undermines them.",
    rows: [
      "Arrogant, hard-headed, selfish, above others", "Avoids danger, risk, and effort to the very last",
      "Easily angered, emotional, impulsive, reactive", "Too trusting, easily deceived, naive, weak-willed",
      "Takes unnecessary risks, and dangers, impatient", "Jealous, manipulative, quite resentful of others",
      "Indecisive, struggles to make choices, hesitant", "Intruding, boastful, exaggerates everything",
      "Cruel, enjoys causing pain, lustful and greedy", "Self-destructive, pessimistic, easily frustrated",
      "Fearful, avoids confrontations,weak-spirited", "Suspicious, paranoid, constant insecurity",
      "Judgmental, intolerant, short-sighted at times", "Full of guilt, riddled and haunted by their past",
      "Sarcastic, hardly serious, sassy, hard to like", "Overprotective, caring, puts others first",
      "Unforgiving, resentful, and easily vindictive", "Superstitious, strong believer, faith before all",
      "Emotionally detached, cold-hearted, uncaring", "Hypocritical, tends to lie, tries to be liked by all",
    ],
  },
  {
    id: "character-weapon", section: "character", group: "Character", page: 14, die: 20,
    name: "by their weapon",
    blurb: "How they defend themselves.",
    rows: [
      "Unarmed, bare hands, at least apparently", "Bone brass knuckle, or some self-defense",
      "Knife, or equivalent melee piercing", "Cleave, or equivalent small blunt weapon",
      "Single-hand military melee weapon", "Two-handed military large melee weapon",
      "Extremely large and heavy melee weapon", "Short range ballistic weapon",
      "Medium range ballistic weapon", "Long range ballistic weapon",
      "Grenade, or throwing explosive weapon", "Throwing weapons, like a throwing-knife",
      "Exotic short-range weapons like Shuriken", "Exotic melee weapon like a whip or net",
      "Peaceable explosives, like a mine or trap", "Toxin or chemical based preparations",
      "Portable large weapons or anti-vehicle", "Mobile turret or suppression weapons",
      "Complex ranged weapons like a crossbow", "Non-weapon based skill or utility, other",
    ],
  },
  {
    id: "character-possessions", section: "character", group: "Character", page: 14, die: 20,
    name: "by their possessions",
    blurb: "What they carry around.",
    rows: [
      "Rich, wealthy, fancy clothes, ornaments, rings", "Poor, rags, bad clothing, dirty, bad smell",
      "Weapon, a gun, a sword, knife, attack item", "An exotic object, a curiosity, an artifact",
      "Bag, briefcase, cargo, supplies, merchandise", "Armor, defense equipment, shields, protection",
      "Book, notepad, notebook, laptop, tablet, scroll", "Hand working tool, crafting, mining, workshop",
      "Specialized tool, laboratory, analysis equipment", "Companion, friend, bodyguard, follower, pet",
      "Vehicle, transport, horse, ride, or keys of", "Hobby or profession object for music or art",
      "Implants, prosthetics, mutation, or extension", "Drink, food, cigarette, consumable, drugs",
      "Personal value, family possession, a symbol", "Faction symbol, badge, tattoo, uniform",
      "Money, valuable, treasure, gold, shiny things", "A special item, magical, high-tech, or divine",
      "Keys, access card, confidential information", "Gadgets, scout equipment, intel, high-tech",
    ],
  },
  {
    id: "character-past", section: "character", group: "Character", page: 15, die: 20,
    name: "by their past",
    blurb: "Where they came from.",
    rows: [
      "Mostly normal, regular childhood and family", "Disturbed childhood, problematic parents",
      "Uneducated, or poverty childhood", "Health issues all along the growth",
      "Experienced war and drama in childhood", "Professional career and studies",
      "Mostly craftsmen work, uneducated", "Individually trained by a field specialist",
      "Nobility-raised, of an important family", "Rich-raised, with plentiful resources",
      "Orphaned and raised in an institution", "Nomadic or traveling community growth",
      "Raised in absolute or mostly isolation", "Went through an extreme traumatic event",
      "Religious upbringing, philosophical living", "Grew in a criminal dangerous environment",
      "Under strong standards of code and honor", "Raised in secret, or with unknown heritage",
      "Put under pressure of achieving big things", "Independent childhood, self-raised",
    ],
  },
  {
    id: "character-activity", section: "character", group: "Character", page: 15, die: 20,
    name: "by their activity",
    blurb: "What they are doing when you meet them.",
    rows: [
      "Looking for something, investigating, searching", "Lost, looking, confused, finding their way",
      "Working, busy, very active, doing things", "Sitting by, idle, chilling out, relaxing, smoking",
      "Defending something, protecting, guarding", "Reading, analyzing, researching, writing",
      "Eating, cooking, drinking, preparing something", "Walking, going somewhere, moving away",
      "Training, working out, exercising, practicing", "Taking care of things, gardening, cleaning",
      "Trading, selling, making business, dealing", "Playing, getting entertained, having fun",
      "Meditating, thinking, concentrated, focused", "Investigating, researching, analyzing, studying",
      "Talking, giving orders, negotiating, socializing", "Fighting, defending himself, attacking",
      "Protesting, shouting, having an argument", "Crafting, building, or repairing something",
      "Meeting, planning, coordinating, deciding", "Practicing magic, a ritual, praying, witchery",
    ],
  },
  {
    id: "character-impression", section: "character", group: "Character", page: 15, die: 20,
    name: "by their impression",
    blurb: "How they look right now.",
    rows: [
      "Tough, athletic, strong, muscles", "Thin, weak, defenseless, small",
      "Tall, large, gigantic, fat, slow", "Exotic, different, distinct, weird",
      "Hurt, injured, dying, weakened", "Sick, debilitated, poisoned, faint",
      "Crippled, slow, trapped, hindered", "Agile, flexible, fast, sneaky, nimble",
      "Scared, afraid, pinned down, taunted", "Hesitant, insecure, nervous",
      "Angry, infuriated, enraged, upset", "Happy, cheerful, easy going",
      "Sad, crying, desperate, lonely", "Crazy, weird eyes, mad, gone",
      "Lost, confused, unsure, hesitant", "Paranoid, altered, exalted, unsettled",
      "Anxious, restless, unsettled, nervous", "Intimidating, bully, bad guy, tough",
      "Relaxed, chill, enjoying the moment", "Drunk, on drugs, possessed",
    ],
  },
  {
    id: "character-intentions", section: "character", group: "Character", page: 15, die: 20,
    name: "by their intentions",
    blurb: "What they want from you.",
    rows: [
      "Protect his stuff, belongings, items", "Make money, trade, sell you something",
      "Make you go away, leave them alone", "Make you stay, invite you, need you",
      "Help you, assist you, give you a hand", "Pay you, hire you, bribe you, for them.",
      "Open up, tell you a story, be heard", "Convince you, persuade you, make you",
      "Stop you, warn you, block you, dissuade", "Hear you, curious about you, ask you",
      "Explain to you, give information, teach", "Spy on you, follow you, track you",
      "Scare you, intimidate you, taunt you", "Exchange information, talk to you",
      "Join you, be with you, to be defended", "Present you someone else, refer to",
      "Learn from you, copy you, be like you", "Control you, monitor you, beware",
      "Inspire you, motivate you, energize you", "Lie to you, manipulate you, hate you",
    ],
  },
  {
    id: "archetypes-1", section: "character", group: "Archetypes", page: 16, die: 100,
    name: "Quick character archetypes 1",
    blurb: "A hundred ready-made character archetypes, first half of the list.",
    rows: [
      "Absent Father: Left his family or was never involved", "Absent-Minded Professor: Intelligent but distracted",
      "Addict: Character addicted to something", "Ambitious Queen: A queen wanting to gain power",
      "Angry Chef: To the detriment of himself and others", "Anthropomorphic Personification: Abstract given form",
      "Anti-Hero: Lacks heroic traits like idealism and morality", "Authority Figure: Someone in a position of power",
      "Author Surrogate: Author living in their own world", "Backstabbing Friend: A friend who ultimately betrays",
      "Bad Boy: A rebellious boy or man who doesn’t care", "Bad Friend: Gets it all wrong, whether they try or not",
      "Bard: Storyteller and music-maker singing tales", "Believer: Character with conviction, or strong beliefs",
      "Benevolent Ruler: A ruler who is compassionate", "Blind Seer: A sightless woman who can see the future",
      "Boss: A person in a position of power, delegating", "Boy-Next-Door: Wholesome boy who is handsome",
      "Bully: A character who hurts others for themselves", "Bumbling Sidekick: An incompetent companion",
      "Bureaucrat: They insist on always following the rules", "Bruce Lee Clone: Character competent in martial arts",
      "Tortured Hero: Usually arrogant, broody, romantic", "Career Criminal: They won’t let handcuffs hold them",
      "Caretaker: Taking care of others before themselves", "Catalyst: Sets everything in motion and move forward",
      "Childhood Friend: Close with the hero in childhood", "Child Savior: Child who is the chosen to save others",
      "Chosen One: The only one who can defeat an evil", "Chooser of the Chosen One: Often an older mentor",
      "Christ-Figure: all-loving figure sacrifices themselves", "Cinderella: Young, beautiful woman treated poorly",
      "Class Clown: Acts silly and funny to make friends", "Comic Relief: Break dramatic tension with small jokes",
      "Complicated Past: Makes their motivations a mystery", "Con Artist: Know how to get what they want",
      "Contender: An underdog you can’t help but root for", "Coward: One who is afraid of pain, shame, or harm",
      "Crazy Cat Lady: Has enough cats. Lonely, unhinged", "Creepy Twins: Identical twins who appear unsettling",
      "Damsel in Distress: Ill-fated woman waiting for rescue", "Dark Jester: A joker hiding dark intentions in sarcasm",
      "Deformed: Someone as “ugly”; treated like a monster", "Devil Incarnate/Dark Lord: Archetype of devil figure",
      "Devotee: Entirely devoted to leader or cause, fanatic", "Divorced Dad: Usually has a child, looking for a date",
      "Double Agent: Working against a faction from inside", "Dreamer: More involved in dreaming than practicality",
      "Dumb College Student: Only knows how to party", "Easy Adapter: Able to adapt to any kind of situation",
      "Eccentric Foreigner: From a foreign land, weird", "Elderly Master: Teaches younger ones a tradition",
      "Emotionally Repressed: They repress themselves", "Empath: Feels the pain of others, wants to help",
      "Enabler: Supports other’s decision despite belief", "Eternal Klutz: Particularly clumsy. Fall in all traps",
      "Everyman: Regular person to represent masses", "Evil Matriarch: An older, evil influential woman",
      "Experiment Gone Wrong: Mad scientist’s creation", "Explorer: Rarely happy in one place, adventurer",
      "Femme Fatale: Uses her beauty and cunning", "Final Girl: Resourceful girl who is the last alive",
      "Friendly Rival: Rival competitor, also a motivation", "Fallen: Attempts or succeed to turn good into evil",
      "Guardian Grandparents: Guardians of a child", "Audience representative: Relatable to the reader",
      "Generic Horror Girl: Girl making every bad choice", "Generic Slasher: The horror or slasher villain",
      "Genius: Smart and logical, bad with emotions", "Gentle Giant: Friendly and warm, despite size",
      "Gentleman Thief: A thief but with good manners", "Gifted Child: A child with extraordinary talents",
      "Girl-Next-Door: Wholesome girl who is pretty", "God: Spiritual being. With some human-like traits",
      "Traditional Hero: Good guy, paladin, fights evil", "Good Samaritan: Character who tries to do good",
      "Time Traveler: Wants to change past and future", "Grieving Widow: Grieving the loss of a partner",
      "Groupie: Someone who hangs around a band", "Guide: Someone who guides a hero all along",
      "Hard-boiled Detective: Solves crimes by trying", "Hard-worker: Hard hours for their betterment",
      "Harsh Judge: Their decision is harsh and swift", "Hedonist: The life goal is the pursuit of pleasure",
      "Hermit: A typically older man who lives alone", "Hippy: Make peace, not war. Emphatic. Idealistic",
      "Hopeless Romantic: They love the idea of love", "Human-Like Creature: An alien, monster, a beast",
      "Human Plot Device: Moves the plot forward", "Hunchback: Treated like a monster but is good",
      "Idiot Turned Hero: An awkward wannabe hero", "Impostor/Pretender: On one side, or the other?",
      "Innocent: Impacted by other’s actions, a victim", "Innovator: Their inventions drive to a golden era",
      "Invasive Neighbor: Gossipy and quite intrusive", "Jaded Lead: Lacks many of the useful qualities",
      "Jock: Great at sports and usually loved by all", "Joker: Funny, but ridicules others’ insecurities",
      "Journalist: Risk their lives to know everything", "Leader: Commands respect from others",
    ],
  },
  {
    id: "archetypes-2", section: "character", group: "Archetypes", page: 17, die: 100,
    name: "Quick character archetypes 2",
    blurb: "A hundred more archetypes, second half of the list.",
    rows: [
      "Liam Neeson: He will find you and he will kill you", "Liar: Character who consistently can’t tell the truth",
      "Living Legend: One of extreme fame and influence", "Logician: Runs purely off of reason and scoffs emotion",
      "Loose Cannon: Law bringer off the rails, taking action", "Lovable Pervert: Perverted character still in good light",
      "Love Interest: Would do anything to win them over", "Macho Action Guy: Strong, good-looking, good fighter",
      "Mad Scientist: Does unconventional experiments", "Mage/Shaman: Magical powers coming in aid",
      "Maiden: Lovely woman with purity and innocence", "Martyr: Willing to die for their beliefs or cause",
      "Masked Superhero: Doesn’t want their identity known", "Masochist: Engages pain and suffering. Visionary?",
      "Maverick: Independent loner who prefers to be alone", "Mentor: An often older and wise supportive person",
      "Messenger: A bearer of truth or news, good or bad", "Messiah: A liberator of the oppressed and believers",
      "Momma’s Boy: Will listen to anything his mom says", "Monk: Tries to act in accordance with their faith",
      "Monster: Scary creature or person who poses a threat", "Matriarch: Nurturing woman offers guidance. But evil?",
      "Mr. Fix It: Insists he can fix anything, physical or not", "Narrator: Storyteller, omnipresent, shares wisdom",
      "Nature Lover: Loves to be in natural places, affinity", "“Nice Guy”: Selfish guy who swears he’s nice but isn’t",
      "Non-Conformist: Rebel who does not believe in norms", "Outcast: One who seems to never quite fit anywhere",
      "Out-of-Towner: Mysterious stranger who is outsider", "Overly Patient Wife: Puts up with difficult spouse",
      "Conspiracy Theorist: Nothing is never a coincidence", "Patriarch: An authoritative man at the head of a family",
      "Peacemaker: To be the voice of peace and reason", "Perfectionist: They can’t let it go, stronger than them",
      "Perpetual Traveler: Wandering in search of something", "Philosopher: Asks profound questions about things",
      "Pinning Friend: Who wants to be more than friends", "Predator: Willing to feed on any who cross their path",
      "Prey: A victim of a predator, sole focus is to survive", "Prince on White Horse: Rescues a damsel in distress",
      "Psychopath: No sense of morality or duty to others", "Puppeteer: Pulling strings behind the scenes",
      "Rags to Riches: Poor who comes into money by luck", "Reluctant Hero: Never wanted to become important",
      "Reluctant Monster: Doesn’t want to be a monster", "Rich Woman: With riches and influence and show it",
      "Rightful Heir: Child who shrugs off their royal roots", "Rightful King: Confronts an evil or illegitimate ruler",
      "Robin Hood: Takes from the rich to give to the poor", "Romantic Runner-Up: Left behind after love triangle",
      "Royal Usurper: Taken the throne illegitimately", "Savant: Someone who is exceptionally talented",
      "Scapegoat: One blamed for another’s actions", "Scrooge: Distant or outright aggressive to others",
      "Secretive: Mysterious and has an unsaid secret", "Servant/Slave: To serve against their own will",
      "Shapeshifter: Not what they appear; dangerous", "Sherlock Holmes Type: Solve mysteries skills",
      "Sickly: Constantly frail, or weak, in a struggle", "Skeptic: Rejects or unconvinced of certain beliefs",
      "Sleazy Politician: Engage in unethical practices", "Soubrette: Young, frivolous and flirtatious woman",
      "Southern Belle: Heavy accent, flirtatious manners", "Role Model: Serves as a good parental figure",
      "Crossed Lovers: Romantic pair doomed to fail", "Starving Artist: Poor but with passion and talent",
      "Straight Man: Serious, makes the fool look worse", "Student: Always trying to learn new things",
      "Stupid Muscle: Little intelligence but helpful", "Super Soldier: Engineered to be clearly superior",
      "Surprise Genius: Unexpected to displays brilliance", "Survivalist: Has great survival skills and training",
      "Survivor: Somehow survives against any odds", "Thrill-Seeker: They’re here for a good short time",
      "Time Traveler’s Wife: A love beyond time/space", "Tortured Superhero: Fights because of a tragedy",
      "Town Drunk: Instantly recognizable to everyone", "Traditionalist: They would rather live in the past",
      "Tragic Hero: Hero with a tragic flaw that goes bad", "Trickster: Plays tricks and disobeys conventions",
      "Troubled Teenager: Rebellious with a rough past", "Truth Seeker: Devoted to finding either a truth",
      "Troubled Vet: Veteran who suffers war effects", "Turncoat: Potentially a traitor, switches sides",
      "Tyrant: Rules with an iron fist, careless to others", "Henchman: Serves and follow a person of power",
      "Unfortunate Orphan: Lost family in childhood", "Unknown Threat: Lurking in the shadows",
      "Unlikely Hero: Everyday person forced to act", "Vampire: Preys on blood of others (literally or not)",
      "Vigilante: Takes justice into their own hands", "Visionary: Strives for change despite odds",
      "Warrior: Defined by their courage and strength", "Wannabe Hero: Looks up to an actual hero",
      "Good Extremist: Goes too far in the name of good", "Whiskey Priest: Do as he says, not as he does",
      "Wicked Stepmother: The one that favors their kid", "Wicked Witch: Evil matriarch using foul magic",
      "Wise Mentor: Wise and sharp teacher figure", "Workaholic: Obsessed with work; has to be",
    ],
  },
  {
    id: "good-purposes", section: "character", group: "Purpose", page: 18, die: 100,
    name: "Good purposes or motivations",
    blurb: "Why a good character does what they do.",
    rows: [
      "Make an offering to a temple", "Help an enemy make things right",
      "Give inspiration and courage", "Fix a broken device or object",
      "Defeat a powerful enemy", "Rescue someone from falling",
      "Help an elderly or weak person", "Pay tribute to the gods or cult",
      "Untangle an evil or secret organization", "Rescue someone from a fire",
      "Help someone injured get to safety", "Show mercy to a defeated enemy",
      "Bring down a tyrant from power", "Be part of a long-term project",
      "Be part of an important battle", "Protect the nature and the living",
      "Lead a team or squad to victory", "Participate in a find and rescue mission",
      "Help with clothing and warmth", "Sacrifice a family object for a cause",
      "Support or help a desperate family", "Educate or foster a child",
      "Help defend a town or village", "Defeat bandits and outlaws",
      "Destroy a valuable but evil artifact", "Listen to someone’s problems",
      "Give council to someone important", "Protect an envoy or caravan",
      "Volunteer to an organization", "Stop the spreading of false information",
      "Forgive someone of a wrong deed", "Defend the king or president",
      "Discover the truth of a murder", "Donate books or knowledge",
      "Help with food and shelter", "Sabotage an act of corruption",
      "Repair critical machinery", "Support with weapons",
      "Help prepare some defenses", "Participate in a rebellion",
      "Help avoid a battle or fight", "Uphold the truth and justice",
      "Give someone a ride or transport", "Confront a terrible evil with courage",
      "Bring light to a dark place", "Support a minority culture",
      "Recover a stolen object", "Support a lost or minority cause",
      "Help a friend or colleague in need", "Bring back hope to the hopeless",
      "Bring a couple together", "Find true love or friend",
      "Follow a personal dream", "Become a master of disguise",
      "Unearth a terrible conspiracy", "Overcome an impossible obstacle",
      "Leave the world a better place", "Share a special knowledge",
      "Create a masterpiece", "Master a form of magic",
      "Avenge a great injustice", "Forge a powerful alliance",
      "Journey to an unknown land", "Retrieve a stolen item",
      "Unearth an ancient secret", "Return something to rightful owners",
      "Shed light on an obscure mystery", "Reconcile with a family member",
      "Put an end to a hazardous situation", "Achieve a monumental feat",
      "Help someone in need", "Unearth a lost civilization",
      "Avenge a wronged ancestor", "Help a friend at all costs",
      "Conquer a great feat of strength", "Overcome a personal fear",
      "Change a person or group's fate", "Save a species from extinction",
      "Find peace and purpose", "Disobey an unjust law",
      "Help a village in crisis", "Put a stop to a villain's plans",
      "Take a stand against injustice", "Find redemption or innocence",
      "Compel a powerful force to retreat", "Liberate a people from tyranny",
      "Find a missing relative", "Rescue a trapped soul",
      "Become a hero of legend", "Uphold a sacred oath",
      "Uncover the secrets of the afterlife", "Embark on a personal pilgrimage",
      "Promote global understanding", "Unlock a hidden potential",
      "Become the confidante of a figure", "Become a legendary warrior",
      "Overcome a personal trauma", "Overcome a great personal challenge",
      "Establish peace between two factions", "Become a beacon of hope",
    ],
  },
  {
    id: "evil-purposes", section: "character", group: "Purpose", page: 19, die: 100,
    name: "Evil purposes or motivations",
    blurb: "Why a wicked character does what they do.",
    rows: [
      "To guard a secret, a legacy", "To make a point, convert others",
      "Alter someone’s fate, or destiny", "Sadism, fun, entertainment",
      "Jealousy, envy, revenge, anger", "To produce chaos and despair",
      "Restore the past, or balance", "Control, dominance, conquest",
      "Create a legacy, long-lasting change", "Destroy a legacy, history or culture",
      "Greed for money and wealth", "Greed for resources, or supplies",
      "Greed for knowledge, or understand", "Greed for magic, or superpowers",
      "Greed for political power, manipulate", "Following a dark path, or ritual",
      "Self-preservation, survival, endure", "To create a new order, or faction",
      "Greed for territory, domain, control", "Evil for its own sake, to be evil",
      "Fix a wrong ideal or a paradox", "Because of pain, suffering, sickness",
      "To cause pain, suffering, injuries", "Mental illness, psychosis",
      "Social pressure or anxiety", "Political pressure, manipulated",
      "Selfishness, egoism, pride", "Fanaticism, religion, ideal",
      "Intolerance, oppression, control", "To deny the truth, or reality",
      "Hatred of social classes or structure", "Hatred of races or different beings",
      "Hatred of religions and extremists", "Hatred of ideologies and biases",
      "Hatred of law, order, and justice", "Hatred of the rich or aristocrats",
      "Being forced, or mental-control", "Hatred of authority, or power",
      "Hatred of the state or government", "Hatred of tradition and culture",
      "Hatred of science and knowledge", "Hatred of progress or evolution",
      "Hatred of technology or science", "Hatred of change or progress",
      "Hatred of education, or children", "Hatred of libraries or documents",
      "Hatred of art, culture, music", "Desire to be admired or loved",
      "Hatred of social norms, regulations", "Hate of people in general, everyone",
      "Fear of death, panic, survival, hunger", "Fear of the unknown, what is yet to come",
      "Fear of failure, or damnation", "Fear of the future, or the end of the world",
      "Fear of the past, the legacy, open strings", "Hearing voices, spirits, demons",
      "Strong belief in doing what is right", "Following orders, or a mandate",
      "Immortality or longevity, long life", "A need to punish, apply force",
      "A need to control, subjugate, dominate", "A need to manipulate, lie, or deceive",
      "A need to be feared", "A need to be respected",
      "A need to be superior", "A need to be powerful",
      "A need to be admired", "A need to be followed",
      "Corrupting influence of money", "Corrupting influence of power",
      "Corrupting influence of ambition", "Corrupting influence of materialism",
      "Corrupting influence of peer pressure", "Under influence of toxic consumables",
      "Corrupted by rumors or media", "Corrupting by the will of the masses",
      "Corrupted by a strong addiction", "Corrupted by a strong superstition",
      "Belief in a false god, or the beyond", "Belief in a destructive ideology",
      "Belief in a dangerous cult or organization", "Desperation, need, unjustifiable reason",
      "Defy a prophecy, whatever the cost", "Fulfill a prophecy, whatever the cost",
      "Compulsion, impulse, lack of control", "Satisfy addiction, craving, a need",
      "An attempt to escape reality", "An attempt to escape guilt or shame",
      "An attempt to cover up a mistake", "An attempt to protect someone or something",
      "An attempt to force conformity", "An attempt to manipulate or exploit",
      "An attempt to gain favor or favoritism", "An attempt to take advantage of a target",
      "An attempt to destroy a rival or enemy", "An attempt to satisfy a warped sense of justice",
      "An attempt to remain anonymous", "An attempt to gain notoriety or popularity",
      "An attempt to become infamous", "An attempt to vent anger, or frustration",
    ],
  },
  {
    id: "good-deeds", section: "character", group: "Purpose", page: 20, die: 100,
    name: "Good intentions or deeds",
    blurb: "A good act, done or intended.",
    rows: [
      "Seek revenge on a person or enemy", "Escape a difficult situation",
      "Rescue a loved one", "Fulfill a sacred mission",
      "Become the leader of a country", "Protect a place of power",
      "Find a way to save the world", "Restore balance to a chaotic system",
      "Acquire wealth and power", "Make a name for themselves",
      "Uncover the truth of a mystery", "Defeat a powerful enemy",
      "Find a way to be accepted in society", "Prove their worth to another individual",
      "Start a rebellion or rebel gang", "Right a wrong from their past",
      "Reunite with a lost love", "Achieve immortality",
      "Unlock the secrets of the universe", "Overcome physical or mental struggle",
      "Get justice for an injustice", "Protect a special object",
      "Avenge the death of a loved one", "Pursue knowledge and wisdom",
      "Bring a group of people together", "End a war or struggle",
      "Create or live in a utopia", "Become a master of a craft",
      "Resolve a family conflict", "Become a master of a martial art",
      "Obtain magical powers", "Satisfy a deep curiosity",
      "Become the ruler of a land", "Live out a prophecy",
      "Find a forbidden item", "Obtain a secret or information",
      "Track down a missing person", "Experience a great adventure",
      "Take on an impossible task", "Uncover secrets of the past",
      "Defeat an ancient enemy", "Fulfill a sacred prophecy",
      "Restore order from a chaotic situation", "Vanquish a great evil",
      "Bring justice to wronged innocents", "Find a hidden treasure",
      "Conquer a great mountain", "Discover the origin of a magical power",
      "Come to terms with a traumatic event", "Transform a place of darkness into light",
      "Rescue someone from drowning", "Visit the sick and injured in hospital",
      "Face a danger to help somebody", "Give an enemy a second chance",
      "Achieve peace between enemies", "Help make friends of two enemies",
      "Help with research or investigation", "Scout an undiscovered danger zone",
      "Support a vulnerable community", "Offer words of encouragement",
      "Join a minor or losing faction", "Make redemption or ask forgiveness",
      "Take care of creature or beast", "Endure pain to protect others",
      "Right a wrong or injustice", "Pay respect to the dead",
      "Find and rescue a child", "Give away a family relic",
      "Bring medical supplies to a healer", "Bring a murderer to justice",
      "Stop an enemy from doing harm", "Have courage to tell a harmful truth",
      "Rescue hostages or prisoners", "Help an injured soldier in battle",
      "Defend someone falsely accused", "Rescue a dying creature",
      "Participate in a disaster relief effort", "Help with infrastructure repair",
      "Respond a call of an ally in need", "Donate work supplies and tools",
      "Solve a complicated problem", "Refuse to take revenge in a hard time",
      "Make a promise to somebody", "Fight alongside an enemy",
      "Defend an innocent from harm", "Build a home or community building",
      "Help lifting a curse or witchcraft", "Sacrifice something for greater good",
      "Fight alongside a friend to the end", "Secure dangerous roads from bandits",
      "Offer craftsman or specialist training", "Offer shelter, or protection",
      "Find books, lore or knowledge", "Help with financial planning",
      "Defend someone in danger", "Take care of a creature or beast",
      "Train someone to defend themselves", "Play an important role in war logistics",
      "Heal or save someone from death", "Provide means of transportation",
    ],
  },
  {
    id: "evil-deeds", section: "character", group: "Purpose", page: 21, die: 100,
    name: "Evil intentions or deeds",
    blurb: "A wicked act, done or intended.",
    rows: [
      "Kill, murder, assassinate someone", "Make an act of stealing or robbery",
      "Intentionally lie in detriment of others", "Conspire to start a war among others",
      "Raid and burn a village or location", "Sacrifice others for own goals",
      "Destroy religious artifacts", "Conduct slavery or kidnapping",
      "Exercise oppression by force", "Betray someone by surprise",
      "Sabotage own faction operations", "Destroy houses, farms, set on fire",
      "Unfair actions or choices upon others", "Exercise religious intolerance",
      "Conduct a violent assault or battle", "Violence, raiding, looting",
      "Vandalism and destruction", "Torture or extortion for a demand",
      "Join or recruit for an evil force", "Spying, sabotage, mind control",
      "Give means of destruction to a faction", "Vandalism and destruction",
      "Send thugs or assassins to kill", "Accept or exercise bribery",
      "Sabotage machine or vehicle", "Corrupt the innocent, force ill actions",
      "Destruction of nature or sources", "Abuse of power, ability or magic",
      "Exploitation of workforce", "Sabotage city defenses to help attacker",
      "Pay respect to an evil god or cult", "Destruction of old ruins and remnants",
      "Be part of kidnapping and trafficking", "State terrorism or vandalism",
      "Support rises of tyranny or an old evil", "Start an unjustified war or conflict",
      "Do evil for a supposed greater good", "Usurp a powerful or political position",
      "Assault a location with innocents", "Allowing or witness unjust suffering",
      "Conquer, colonize, override culture", "Hunting of creatures, beasts, preys",
      "Neglect respect of hierarchy or an order", "Squander resources and sabotage",
      "Refusal to help someone in need", "Manipulating others for benefit",
      "Operate illegal gambling or business", "Ignore injustice or an ill act",
      "Seduction for manipulation", "Conduct burglary, bank robbery",
      "Kill a trader, merchant or businessman", "Kill a governor, noble or politician",
      "Leave behind an ally in need", "Take wrath or revenge an innocent soul",
      "Acts of deception and manipulation", "Creating dispute or conflict in others",
      "Be a false witness or lie to the law", "Prevent someone from recovering",
      "Hindering progress or sabotage a town", "Hide true motives from high powers",
      "Imprisonment and torture of an innocent", "Forcing of unwanted marriage for power",
      "Drug trafficking or smuggling", "Refuse to peace or stop a conflict",
      "Hide a secret that could save lives", "Praising or encouraging evil factions",
      "Selling secrets, intel, whistleblowing", "Transport hostages or prisoners",
      "Conduct an ambush or stealth operation", "Order to destroy a group or faction",
      "Lead a gang, mafia or troublemakers", "Steal from the vulnerable, corruption",
      "Recover or usurp an evil artifact or power", "Give an artifact to the wrong hands",
      "Fake an identity or conduct forgery", "Create or summon monsters or creeps",
      "Develop or research a lethal weapon", "Raise armies, monsters, or mercenaries",
      "Hunt down a minor or weak faction", "Making false promises to people",
      "Conduct piracy or raid convoys", "Prey down on the weak and vulnerable",
      "Decide not to save someone from death", "Denying the truth to someone",
      "Unfair trading or black market", "Cast away, banish or execute people",
      "Spread poison, plague or curse", "Refusal to respect faith or culture",
      "Raise the dead, necromancy", "Conduct dark rituals, blood, black magic",
      "Build secret lairs, illegal facilities", "Destroy lore, history, books, knowledge",
      "Sabotage someone’s attempt to do good", "Break a promise, disappoint someone",
      "Hunt down a family or legacy", "Refuse to forgive or have piety",
      "Promote false or malicious information", "Deal torture experiments for knowledge",
      "Loot from fallen corpses or the dead", "Spread fear and terror to control",
    ],
  },
  {
    id: "grand-action", section: "grand", group: "Grand oracle", page: 22, die: 100,
    name: "Action",
    blurb: "A verb. Combine with an adjective and a subject for anything at all.",
    rows: [
      "Achieve, succeed, triumph, press on, push, reinforce", "Allow, grant, permit, authorize, enable, allow, let",
      "Encourage, instigate, stimulate, excite, motivate", "Believe, have faith, trust, be confident on, rely on",
      "Call, rally, reunite, meet, group, summon, gather", "Change, transform, evolve, mutate, alter, become",
      "Claim, seize, capture, occupy, take, conquer", "Continue, double the effort, press harder, push",
      "Divide, separate, split, disjoint, break, tear, pull", "Schedule, prepare, organize, arrange, plan, lead",
      "Solve, figure out, answer, decipher, deduce, untangle", "Follow, chase, pursue, track, spy, recon, shadow",
      "Help, aid, assist, heal, support, care, treat", "Hold, keep, defend, protect, stand, alert, alarm",
      "Identify, recognize, associate with, reminds to", "Strengthen, empower, reinforce, fortify, improve",
      "Keep, hold on to, retain, stay, carry on with, sustain", "Know, learn, understand, translate, note, journal",
      "Soften, give little, alleviate, lessen, minimize", "Conjure, spell, cast, recite, radiate, evoke, emanate",
      "Make, create, define, construct, establish, produce", "Need, require, want, demand, crave, desire",
      "Offer, give, provide, present, gift, grant, trust", "Buy, acquire, purchase, trade, obtain, haggle",
      "Reach, make it to, go to, hike up, travel, extend", "Reduce, shrink, bring down, turn down, diminish",
      "Respect, love, regard, admire, have courtesy", "Deal with, take care of, handle, manage, organize",
      "Seem, show off, appear to be, act as, fake, brag", "Envoy, message, dispatch, transmit, communicate",
      "Serve, be in the service of, obey, follow, trust", "Research, investigate, study, read, explore, seek",
      "Take, steal, raid, sabotage, secure, confiscate, get", "Travel, go to, advance, move, transport, teleport",
      "Worship, adore, respect, be fanatic of, exaggerate", "Accomplish, succeed, win, fulfil, achieve, deserve",
      "Reveal, admit, give away, confess, tell, allow, show", "Arise, grow, come to light, appear, emerge, stand up",
      "Sell, trade, exchange, deal, get rid of, get done with", "Attack, invade, strike, charge, assault, storm, siege",
      "Empathize, sympathize, understand, commune", "Begin, start, initiate, launch, set up, kick off, begin",
      "Bluff, lie, deceive, betray, feint, cheat, manipulate", "Break, damage, shatter, smash, crack, poison",
      "Interrupt, cancel, intrude, stop, block, prevent", "Command, give order, instruct, direct, mandate, lead",
      "Catch, grab, hunt arrest, trap, hook, capture, bait", "Challenge, defy, duel, disobey, dare, contradict",
      "Charge, tax, bill, demand, impose, levy, collect", "Condemn, judge, assess, denounce, convict, accuse",
      "Slow down, delay, hinder, postpone, hold back", "Clear, clean up, open up, free, empty, liberate",
      "Close up, near, direct, reach out, approach", "Close, wrap up, finish, complete, conclude",
      "Comply, adhere, obey, stick to, follow rules", "Avoid, evade, dodge, neglect, suppress, withstand",
      "Contact, reach out to, communicate, talk to, refer", "Cover, store, save, hide, keep safe, shelter",
      "Pay for, afford, finance, remunerate, reward", "Allocate, delegate, invest, instate, induct, bet, risk",
      "Decide, choose, determine, resolve, settle, rule", "Observe, watch, monitor, supervise, record, control",
      "Depart, abandon, leave, withdraw, quit, take leave", "Descend, go deep, fall, sink, slope, submerge",
      "Describe, explain, report, express, chronicle", "Disclose, reveal, divulge, spread, pass on, report",
      "Dispatch, send, deploy, ship, transmit, consign", "Drain, channel, pipe, conduct, repurpose, redirect",
      "Ride, handle, operate, steer, navigate, mount, drive", "Eliminate, remove, abolish, delete, destroy, banish",
      "Banish, prohibit, expel, throw out, cast out, dismiss", "Employ, hire, recruit, enlist, appoint, gather",
      "Ask, request, question, discuss, argue, propose", "Encounter, face, engage, confront, come across",
      "Kill, destroy, assassinate, eliminate, suppress", "Enhance, improve, intensify, magnify, strengthen",
      "Ensure, make sure of, secure, warrant, guarantee", "Expect, wait for, look for, await, look forward to",
      "Express, say, share, comment, declare, announce", "Favor, approve, benefit, esteem, like, support",
      "Oppose, fight, disapprove, dislike, reject, react", "Feel, detect, sense, experience, bear, handle",
      "Fight, combat, struggle, dispute, challenge", "Focus, concentrate, direct, centralize, channel",
      "Hear, listen, pay attention, spot, observe, smell", "Honor, respect, commemorate, glorify, commend",
      "Immobilize, disable, cripple, paralyze, knockdown", "Influence, persuade, convince, manipulate, seduce",
      "Invite, gather, reunite, ask, bid, summon, invoke", "Participate, join, be part of, cooperate, bond with",
      "Perform, act, carry out, play, present, stage", "Be praised for, be requested to, be needed for",
      "Provoke, taunt, intimidate, scare, frighten", "Find, search, locate, track down, spot, trace",
      "Prove, show, demonstrate, validate, confirm", "Include, increase, incorporate, merge, aggregate",
      "Realize, discover, uncover, find out, unmask", "Remember, remind, recall, think, ideate, reason",
      "Retrieve, bring back, recover, reclaim, reestablish", "Work, build, tailor, craft, brew, cook, prepare",
    ],
  },
  {
    id: "grand-adjective", section: "grand", group: "Grand oracle", page: 23, die: 100,
    name: "Adjective",
    blurb: "A quality. The middle word of the three.",
    rows: [
      "Abundant, plentiful, loaded, rich, wealthy, charged", "Active, latent, lively, occupied, busy, crowded",
      "Adventurous, dangerous, risky, daring, defiant", "Afraid, scared, paralyzed, macabre, horrific, terrifying",
      "Chemical, alchemical, biological, elemental, organic", "Alien, outsider, unfitting, foreign, different, strange",
      "Aquatic, liquid, watery, oceanic, wet, humid, flooded", "Attacked, damaged, pillaged, hit, bullied, hurt",
      "Barbaric, native, primitive, untouched, savage", "Beautiful, charming, exotic, marvelous, spectacular",
      "Blank, empty, inhabited, clear, void, desolated", "Broken, damaged, dead, non-functional, useless",
      "Careful, tidy, clean, delicate, maintained, cared for", "Cautious, defensive, paranoid, watched, observed",
      "Chaotic, messy, unattended, disastrous, abandoned", "Divine, celestial, godly, sacred, holy, religious",
      "Characteristic, local to this place, belonging, native", "Clouded, foggy, hard to see, fuzzy, invisible",
      "Corrupted, manipulated, utilized, misused, abused", "Crazy, unpredictable, nonsensical, strange, random",
      "Complicated, complex, difficult, cursed, impossible", "Dark, unlit, black, obscure, dim, gloomy, scary",
      "Deadly, dangerous, toxic, decadent, sick, poisonous", "Armed, protected, defended, fortified, ready",
      "Deep, buried, stashed, underground, underwater", "Hot, dry, red, sunny, flat, drained, burning, on fire",
      "Developed, detailed, carefully built, well-presented", "Diplomatic, stylish, well-suited, elegant, presented",
      "Distinct, different, exotic, unique, special, remarkable", "Rocky, mountainous, solid, large, huge, gigantic",
      "Dynamic, moving, agile, unstable, acrobatic, sneaky", "Reachable, welcoming, inviting, hospitable, available",
      "Empowered, enhanced, fortified, improved, upgraded", "Encouraging, inspiring, leading, exemplary, driving",
      "Enigmatic, confusing, curious, distinctive, revealing", "Entertaining, fun, humorous, joyful, cheerful",
      "Essential, important, key, relevant, strategic", "Environmental, meteorological, atmospheric, natural",
      "Expensive, rich, majestic, rare, valuable, shiny", "Fatal, deadly, fearsome, invincible, immune",
      "Foolish, dumb, unprepared, unprotected, vulnerable", "Healthy, repaired, fixed, recovered, constructed",
      "Disguised, concealed, secret, camouflaged, hidden", "Historic, memorable, legendary, old, ancient",
      "Hungry, lacking, needing, depending, thirsty", "Idle, inactive, never used, turned off, disconnected",
      "Impassable, impenetrable, inaccessible, impermeable", "Inhospitable, inhuman, infested, cursed, damned",
      "Irresistible, tempting, seductive, addictive", "Isolated, lonely, separated, introvert, alone",
      "Known, familiar, renowned, predictable, stable", "Limited, insufficient, lacking, incomplete, missing",
      "Little, small, minimal, reduced, shrunk, tiny", "Loud, sound, talkative, noisy, distracting, musical",
      "Loyal, respectful, legal, honorable, proud", "Magical, mystical, wondrous, strange, wizardry",
      "Mighty, powerful, strong, forceful, fierce, vicious", "Monstrous, aberration, horrible, disastrous, twisted",
      "Necessary, critical, crucial, required, needed", "Negative, harmful, unwanted, undesired, avoided",
      "Numerous, filled, quantity, together, grouped", "Clever, intelligent, ingenious, smart, professional",
      "Original, native, cultural, traditional, conventional", "Pathetic, ridiculous, unfitting, weird, strange",
      "Political, strategic, wealthy, designed, planned", "Precarious, poor, lacking, poverty, unwanted",
      "Quick, fast, agile, moving, nimble, sneaky", "Ruin, forgotten, abandoned, destroyed, extinct",
      "Safe, secure, silent, calm, quiet, trustworthy", "Scattered, spread out, distracted, flattened",
      "Selected, chosen, elected, voted, decided", "Shady, illegal, immoral, uncomfortable, wrong",
      "Eliminated, killed, destroyed, annihilated, executed", "Snowy, frozen, still, shattered, cold, glassy",
      "Abnormal, supernatural, different, atypical", "Timed, temporary, time-consuming, demanding",
      "Undead, revived, recovered, restored, repaired", "Undiscovered, new, untouched, born, virgin",
      "Wonderful, amazing, incredible, brilliant, flashy", "Useful, handy, active, convenient, fortunate",
      "Valuable, desired, promoted, expensive, pricey", "Vast, extended, powerful, huge, broad, wide",
      "Visited, concurred, popular, famous, remarkable", "Weak, helpless, vulnerable, exposed, endangered",
      "Plastic, artificial, composite, fictional, fabricated", "Confined, obscured, forbidden, protected, illegal",
      "Open, airy, flowed, accessible, reachable, elevated", "Expanding, enlarging, growing, spreading",
      "Wooden, strong, resistant, metallic, reflective", "Written, recorded, archived, translated, journaled",
      "Mechanical, complex, built, functional, synthetic", "Explosive, delicate, reactive, inflammable",
      "Civilized, urbanized, elegant, decorative, organized", "Captured, taken, stolen, missing, kidnapped",
      "Expelled, banished, forbidden, rejected, prohibited", "Owned, private, personal, enslaved, hired, domain",
      "Violent, enraged, angry, unstable, hysteric", "Friendly, allied, cooperative, helpful, supportive",
      "Modern, technological, advance, revolutionary", "Depleted, used, utilized, tired, exhausted, wasted",
    ],
  },
  {
    id: "grand-subject", section: "grand", group: "Grand oracle", page: 24, die: 100,
    name: "Subject",
    blurb: "A noun. The thing the action happens to.",
    rows: [
      "People, civilian, masses, groups, population, voices", "Protection, defense, preservation, sanctuary",
      "Ability, quality, power, edge, implant, skill, maneuver", "Advisor, counselling, chancellor, ambassador",
      "Entertainment, joy, happiness, festivity, holiday, music", "Promise, an oath, destiny, fate, a vow, pledge, belief",
      "Aftermath, consequences, leftovers, outcomes", "Agreement, a contract, an alliance, arrangement, deal",
      "Archers, rifles, ammunition, long range, artillery, guns", "Ambush, a strike, a coup, revolt, revolution, sabotage",
      "Magic, weird science, esotericism, occult, alien", "An appointment, a new ruler, coronation, ascension",
      "Armor, armory, defense, equipment, shield, protection", "Arrival of someone, people, newcomers, immigrants",
      "Artwork, style, artists, culture, music, expression", "Artifacts, objects of power, amulets, jewelry",
      "Truth, innocence, compassion, empathy, support", "An audience, conference, meeting, council, reunion",
      "Barbaric, nomads, bandits, renegades, outlaws", "Religion, divine, clerics, deities, gods, wrath, faith",
      "Message, omens, communication, news, changes", "Block, blockade, position, wall, barricade, cover",
      "Bravery, courage, overcoming fear, valor, honor", "Weapons, melee, two-handed, sword, axe, hammer",
      "Monster, beasts, robot, machine, creature, being", "Business, trade, commerce, exchange, a deal, ports",
      "Campaign, operation, expedition, project, adventure", "Rest, recovery, a safe place, a pause, hospitality",
      "Carrier, courier, a messenger, a bearer, a runner", "Mountains, hills, cliffs, altitude, elevation, hard, rock",
      "Mockery, insult, offense, disrespect, assault, violation", "Chance, an opportunity, advantage, a moment",
      "Money, supplies, resources, wealth, assets, surplus", "Machinery, engineering, infrastructure, platform",
      "Chronicles, history, events, past, culture, legacy", "City, village, town, settlement, housing, urbanization",
      "Claim, rightfulness, possession, belongings, treasure", "Cloud, visibility, fog, clear thoughts, ideas, sight",
      "Command, mandate, orders, chain of duty, execution", "Companions, allies, supporters, henchmen, assistant",
      "Concealment, privacy, invisibility, transparency", "Conflict, invasion, war, battle, large scale skirmish",
      "Construction, building, structure, ruins, pillars, statue", "Consumables, potions, drugs, toxins, alchemy",
      "Conversation, dialogue, discussion, argument, reason", "Corpse, death, mortality, undead, necromancy, ghost",
      "Countryside, farms, agriculture, surroundings, nature", "Couple, love, partner, passion, sex, jealousy, envy",
      "Crew, brotherhood, fraternity, faction, family, cult", "Kings, rulers, dictators, aristocrats, nobles, ministers",
      "Curse, damnation, sickness, insanity, crazy", "Army, troops, soldiers, mercenaries, recruits",
      "Politics, secrets, rumors, scheming, betrayal", "Danger, threat, hazard, emergency, jeopardy",
      "Dark, darkness, dark side, evil, malevolence", "Devastation, ravage, destruction, ruin, wreckage",
      "Decision, choices, costs, consequences, matter", "Declaration, announcement, statement, saying",
      "Defeat, loss, failure, not enough, frustration", "Desire, power, aspiration, dreams, wishes, ambition",
      "Desolation, absence, loneliness, emptiness, void", "Tools, knowledge, utilities, technology, means",
      "Detection, perception, intuition, feeling, insight", "Development, improvement, growth, expansion",
      "Diplomacy, treaty, politics, influence, power", "Disease, sickness, poison, venom, pandemic",
      "Distraction, detour, a different way, lure, a trap", "Door, gate, passage, bridge, portal, caves, tunnel",
      "Opposition, enemies, adversities, misfortune", "Drama, loss, sadness, emotions, regret, blame",
      "Food, water, resources, minerals, materials", "Dust, earth, sand, sandstorm, desert, mud, rocks",
      "Elimination, assassination, killing, dagger, target", "Empire, kingdom, country, state, civilization, reign",
      "Energy, ritual, catalyst, magic, conjuration, sorcery", "Enthusiasm, energy, activity, eagerness, anxiety",
      "Escape, break out, prison, freedom, flee, free-will", "Time, year, calendar, end of, period, era, age",
      "Fear, scare, horror, terror, paranoia, sanity", "Research, information, lore, knowledge, data",
      "Fire, flame, heat, red, burning, summer, warmth", "Roads, rivers, routes, bottlenecks, shortcut",
      "Forest, Jungle, trees, green, plants, growth, life", "Fortress, castle, outpost, keep, bunker, stand",
      "Water, rain, swamp, cold, ice, snow, liquid", "Plan, strategy, goal, objective, mission, idea",
      "Friend, colleague, relationship, intimate, confidant", "Person, contact, relative, someone, entity",
      "Glory, victory, triumph, success, gains, benefits", "Bacteria, virus, insects, vermin, drones, parasites",
      "Domain, field, territory, land, province, region", "Superiority, perfection, majesty, achievement",
      "Harm, damage, blood, injuries, pain, suffering", "Hatred, anger, vengeance, resentment, envy",
      "Healing, heart, health, recovery, rest, body", "Commander, mercenary, captain, general, soldier",
      "Vehicles, transport, rides, mounts, aircraft, ships", "Hunger, thirst, starvation, breath, survival",
      "Illusion, lies, tricks, traps, thievery, theft, corruption", "Peace, tranquility, nature, harmony, balance",
    ],
  },
];

// Errata: values the book prints that appear to be mistakes. Per the source
// precedence rule, they are recorded and surfaced, never silently corrected —
// the printed table is what a player rolling on paper would get.
export const GUM_ERRATA = [
  {
    id: "G1", page: 21, table: "evil-deeds",
    text: "\"Evil intentions or deeds\" prints \"Vandalism and destruction\" twice, at 17 and at 22.",
    ruling: "Kept as printed, so the app's odds match the book's. Rolling either number gives the same result — treat it as slightly more likely, or re-roll, exactly as you would at the table.",
  },
];

// The blanks GUM is best at filling, by PUM plot-node category (GUM p.3:
// "PUM uses plot nodes, with GUM providing inspiration to fill a plot sheet").


// A plot seed is the book's own combination, in its own order (GUM pp.6-7).
export const GUM_PLOT_SEED = [
  "plot-hook", "motivation", "mission", "initial-lead", "caveat", "opposition",
];

// The three-word roll the Grand oracle exists for (GUM pp.22-24).
export const GUM_GRAND = ["grand-action", "grand-adjective", "grand-subject"];

// --- Which tables a blank field reaches for --------------------------------
// Every text field that GUM can actually serve offers three rolled words. The
// tables are chosen by what the field is *for*, so a character field pulls
// archetypes and flaws while a location field pulls features and purpose.
// Nothing here is new content: the same 43 tables, pointed at a blank.
//
// The rule that decides whether a field appears here at all is SHAPE. Every GUM
// row is a descriptive phrase about fiction — "Humid: wilderness, jungle,
// raining", "Naturally draws others in". That is the right shape for a field
// that wants a piece of fiction, and the wrong shape for a field that wants a
// proper name ("Vera", "The Neverwinter road") or a real-world answer ("D&D
// 5e"). Pointing a table at a field of the wrong shape produces an answer that
// reads as noise, which is worse than no offer at all — see INSPIRE_ABSENT.
//
// A field with more tables than it needs rotates through them on a re-roll; a
// field with fewer rolls several times within the ones it has, which GUM p.3
// names as its own method ("roll multiple times within one table").
export const GUM_FOR_FIELDS = {
  // The eight plot-node lists (PUM p.28 and the p.27 extension).
  world: ["location-archetype", "background-problem", "faction-focus", "faction-society", "faction-politics"],
  problems: ["opposition", "caveat", "nemesis-intentions", "creature-type", "evil-deeds"],
  findings: ["object-function", "object-form", "location-worth", "location-content"],
  questions: ["plot-hook", "initial-lead", "mission", "motivation"],
  characters: ["archetypes-1", "archetypes-2", "character-edge", "character-flaw", "good-purposes"],
  locations: ["location-archetype", "location-feature", "location-purpose", "location-worth"],
  // The two player-named lists (PUM p.27) hold whatever this game needs, so the
  // grand oracle — GUM's own answer to "nothing specific fits" — is what suits.
  custom1: ["grand-action", "grand-adjective", "grand-subject"],
  custom2: ["grand-action", "grand-adjective", "grand-subject"],

  // Game identity (PUM p.3 step 1). "game-title" used to map here on the premise
  // that the grand oracle's adjective and subject tables are "word-shaped", so
  // an adjective plus a subject could be read as a title. That premise is false:
  // NOT ONE of those 200 rows is a single word. Every one is a cluster of four
  // to eight synonyms — "Abundant, plentiful, loaded, rich, wealthy, charged" —
  // so the field that asks you to name your game was offering to paste a
  // thesaurus entry into it. Moved to INSPIRE_ABSENT, where the app says so.
  //
  // Tone asks for "grim frontier fantasy, low magic": what kind of place this
  // is, and what is wrong with it. Both of those GUM has directly, so they lead.
  "game-tone": ["location-archetype", "background-problem", "faction-society"],
  "game-inspiration": ["grand-action", "grand-adjective", "grand-subject"],

  // The plot scope and its mission (PUM p.3 step 2). A scope NAME is a goal
  // stated in a line — "find out who burned the caravan" — and exactly one GUM
  // table is that shape: the mission. A plot hook is an event and a motivation
  // is a reason; neither answers "what is this story about?", and both were
  // being offered here. One table is not too few: rolling several times within
  // one table is GUM p.3's own method, and it yields three candidate goals.
  "scope-name": ["mission"],
  "scope-mission": ["plot-hook", "motivation", "mission", "initial-lead", "caveat", "opposition"],
  "scope-start": ["plot-hook", "initial-lead", "location-archetype"],
  "scope-notes": ["grand-action", "grand-adjective", "grand-subject"],

  // People and places. GUM builds a character as a *concept*, not a name, so
  // these feed the notes beside the name rather than the name itself.
  "protagonist-notes": ["archetypes-1", "archetypes-2", "character-edge", "character-flaw", "character-past"],
  "cast-character": ["archetypes-1", "archetypes-2", "character-edge", "character-flaw", "good-purposes"],
  "cast-location": ["location-archetype", "location-feature", "location-purpose", "location-worth"],
  "cast-notes": ["character-impression", "character-intentions", "character-activity", "character-past"],

  // A coming event, marked on a future box (PUM p.9)
  "timed-beat": ["nemesis-intentions", "opposition", "evil-deeds"],

  // The scene
  "scene-open": ["location-feature", "character-activity", "grand-action"],
};

// Fields the app deliberately does NOT offer a roll on, and why. Recorded the
// way ruling A8 records the absent safety tools: the honest answer is that the
// book has nothing for this, said plainly, rather than a table pointed at the
// wrong question so that every field has *something*.
// A worked example of the plot seed, on the Forge screen itself. Six abstract
// table names ("Caveat", "The opposition") tell a player what the machine has,
// not what it gives them — and the one question they actually have is "what does
// this look like when it works?". Real rows at real die values, like every other
// example in this project: nothing here is written to flatter the tables.
export const GUM_SEED_EXAMPLE = {
  rolls: [
    { table: "Plot hook", die: 20, roll: 4, text: "Someone in power gives you an order" },
    { table: "Motivation", die: 20, roll: 11, text: "A personal matter, backstory related" },
    { table: "The mission", die: 20, roll: 2, text: "Defeat a faction, bandits, or outlaws" },
    { table: "Initial lead", die: 20, roll: 9, text: "Investigate location of a recent event" },
    { table: "Caveat", die: 20, roll: 6, text: "Background problem actively in your way" },
    { table: "The opposition", die: 20, roll: 14, text: "Your backstory is causing them trouble" },
  ],
  reading: "A lord orders you to break up a bandit company — but it is personal: they are tied to your own past, and that past is exactly why they are coming for you. Start at the site of their last raid, with whatever is already wrong in this region getting in the way.",
  // Where each line went. This is the part a player cannot guess.
  became: [
    ["Plot scope name", "Break the bandit company before they reach the valley"],
    ["Starting point", "The raid site, three days cold, with the lord's rider waiting"],
    ["World, tone and theme", "A region with its own standing trouble, indifferent to yours"],
    ["A potential problem", "They know who you are — your past is their grievance"],
    ["The cast", "The lord who gave the order"],
  ],
};

export const INSPIRE_ABSENT = {
  "game-universe": "Which RPG or fiction you are playing in is a real-world answer — D&D 5e, Blade Runner, your own. GUM generates worlds, not the names of published ones.",
  "game-title": "A title is a name you coin, and GUM coins none. Its nearest tables emit clusters of synonyms — \"Abundant, plentiful, loaded, rich, wealthy, charged\" — which is raw material for a mood, not a name for a game. Roll the world and the tone below, then name it after what you find.",
  "protagonist-name": "GUM has no name generator. It builds a character as a concept; the concept goes in the notes beside the name.",
  "cast-rename": "Renaming something that already exists is a correction, not an invention.",
  "list-name": "A plot-node list's name is a category you choose — factions, rumours, debts. GUM has no table of categories.",
  "track-section": "A track section is a structural label for your own pacing, not a piece of fiction.",
  "journal-entry": "The journal records what already happened. Rolling for it would be inventing over your own play.",
  "journal-note": "Same: a note interprets a roll you have already made.",
  "session-break": "A bookmark for where you stopped.",
};

// How many words a roll produces. Three, per the grand oracle's own shape.
export const INSPIRE_WORDS = 3;
